FROM ghcr.io/astral-sh/uv:debian

WORKDIR /app

RUN apt update && apt install git -y && \
    git clone https://github.com/fspecii/ace-step-ui

# Set debconf to run non-interactively
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# install curl
RUN apt update && apt install curl -y

ARG NODE_VERSION=20
# install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash

# set env
ENV NVM_DIR=/root/.nvm

WORKDIR /app/ace-step-ui
COPY /modified_setup.sh ./setup.sh
COPY /start.sh .
# install node
RUN bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && ./modified_setup.sh"

CMD [ "bash", "-c", "./start.sh" ] 
